# Generated by Django 5.2.11 on 2026-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0004_add_livechatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="recording_file",
            field=models.FileField(blank=True, null=True, upload_to="recordings/"),
        ),
    ]
