# Generated by Django 5.2.11 on 2026-07-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0005_add_recording_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveparticipant",
            name="is_admitted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="livesession",
            name="requires_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="livesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("WAITING", "Waiting"),
                    ("LIVE", "Live"),
                    ("ENDED", "Ended"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
