# Generated by Django 5.2.11 on 2026-07-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0006_add_waiting_status_and_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveparticipant",
            name="role",
            field=models.CharField(
                choices=[
                    ("HOST", "Host"),
                    ("CO_HOST", "Co-host"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="livesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("LIVE", "Live"),
                    ("ENDED", "Ended"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
