# Generated by Django 5.2.11 on 2026-07-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_learningpath_tag_course_certificate_template_and_more"),
        ("live", "0007_remove_waiting_add_cohost"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Anyone with the link can join without enrollment.",
            ),
        ),
        migrations.AlterField(
            model_name="livesession",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_sessions",
                to="courses.course",
            ),
        ),
    ]
