# Generated by Django 5.2.11 on 2026-03-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_thumbnail_file_alter_course_slug"),
        ("learning", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="module",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_quiz",
                to="courses.module",
            ),
        ),
    ]
