# Generated by Django 5.2.11 on 2026-07-08 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0004_focussession_skill_userskill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LESSON_STARTED", "Lesson started"),
                            ("LESSON_COMPLETED", "Lesson completed"),
                            ("QUIZ_STARTED", "Quiz started"),
                            ("QUIZ_PASSED", "Quiz passed"),
                            ("QUIZ_FAILED", "Quiz failed"),
                            ("COURSE_ENROLLED", "Course enrolled"),
                            ("COURSE_COMPLETED", "Course completed"),
                            ("CERTIFICATE_CLAIMED", "Certificate claimed"),
                            ("NOTE_CREATED", "Note created"),
                            ("ASSIGNMENT_SUBMITTED", "Assignment submitted"),
                            ("FOCUS_SESSION", "Focus session completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
