# Generated by Django 5.2.11 on 2026-07-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0006_skill_tree_dynamic"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("COURSE_UPDATE", "Course Update"),
                    ("ASSIGNMENT", "Assignment"),
                    ("GRADE", "Grade"),
                    ("MESSAGE", "Message"),
                    ("SKILL_UNLOCK", "Skill Unlock"),
                    ("SYSTEM", "System"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
