# Generated by Django 5.2.11 on 2026-07-27 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0007_notification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("COURSE_UPDATE", "Course Update"),
                    ("ASSIGNMENT", "Assignment"),
                    ("GRADE", "Grade"),
                    ("MESSAGE", "Message"),
                    ("LIVE_SESSION", "Live Session"),
                    ("LIVE_REMINDER", "Live Reminder"),
                    ("SKILL_UNLOCK", "Skill Unlock"),
                    ("SYSTEM", "System"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expo_push_token", models.CharField(max_length=255, unique=True)),
                ("platform", models.CharField(default="android", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
