# Generated by Django 5.2.11 on 2026-08-04 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def publish_existing_grades(apps, schema_editor):
    Submission = apps.get_model("learning", "Submission")
    Submission.objects.filter(status="GRADED").update(is_published=True)


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0008_add_push_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="allowed_extensions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assignment",
            name="instructions_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="assignment",
            name="instructions_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="max_file_size_mb",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="submission",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="submission",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Extension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("new_deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="learning.assignment",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extensions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "student")},
            },
        ),
        migrations.RunPython(publish_existing_grades, migrations.RunPython.noop),
    ]
