# Generated by Django 5.2.11 on 2026-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="audience",
            field=models.CharField(
                choices=[("STUDENT", "Student"), ("INSTRUCTOR", "Instructor")],
                default="STUDENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="badge",
            field=models.CharField(
                blank=True, default="", help_text="e.g. 'Most Popular'", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(
                blank=True, default=list, help_text="List of feature strings to display"
            ),
        ),
    ]
