# Generated by Django 5.2.11 on 2026-07-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_subscriptionplan_audience_subscriptionplan_badge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="stream_minutes_monthly",
            field=models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="stream_minutes_used_this_month",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
