# Generated by Django 5.2.11 on 2026-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail_file",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
