# Generated by Django 5.2.11 on 2026-03-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_thumbnail_file_alter_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="learning_objectives",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="lessons/videos/"),
        ),
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="lessons/resources/"
            ),
        ),
    ]
