# Generated by Django 5.2.11 on 2026-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_learning_objectives_course_prerequisites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="estimated_hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(default="en", max_length=16),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="course",
            name="target_audience",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lesson",
            name="instructor_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("VIDEO", "Video"),
                    ("TEXT", "Text"),
                    ("QUIZ", "Quiz"),
                    ("ASSIGNMENT", "Assignment"),
                    ("LIVE", "Live"),
                    ("DOWNLOAD", "Download"),
                ],
                default="VIDEO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="transcript",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="module",
            name="estimated_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="module",
            name="learning_objectives",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
