# Generated by Django 5.2.11 on 2026-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_learningpath_tag_course_certificate_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("VIDEO", "Video"),
                    ("TEXT", "Text"),
                    ("QUIZ", "Quiz"),
                    ("ASSIGNMENT", "Assignment"),
                    ("DEVOIR", "Devoir"),
                    ("LIVE", "Live"),
                    ("DOWNLOAD", "Download"),
                ],
                default="VIDEO",
                max_length=20,
            ),
        ),
    ]
