# Generated by Django 5.2.11 on 2026-09-16 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_alter_lesson_lesson_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Cours du programme"),
                    ("MARGINAL", "Cours marginal"),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Fin de la période (cours marginal)", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Début de la période (cours marginal)", null=True
            ),
        ),
        migrations.CreateModel(
            name="CourseInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = nombre d'utilisations illimité"
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="courses.courseinvitation",
            ),
        ),
    ]
