import json
from urllib import error, parse, request

from django.conf import settings


class GeminiGenerationError(Exception):
    pass


GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"


def _request_json(prompt: str):
    api_key = settings.GEMINI_API_KEY.strip()
    if not api_key:
        raise GeminiGenerationError("GEMINI_API_KEY is not configured.")

    payload = {
        "contents": [
            {
                "parts": [
                    {
                        "text": prompt,
                    }
                ]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json",
            "temperature": 0.6,
        },
    }
    url = f"{GEMINI_URL}?key={parse.quote(api_key)}"
    data = json.dumps(payload).encode("utf-8")
    req = request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with request.urlopen(req, timeout=45) as response:
            body = json.loads(response.read().decode("utf-8"))
    except error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="ignore")
        raise GeminiGenerationError(detail or "Gemini request failed.") from exc
    except error.URLError as exc:
        raise GeminiGenerationError("Gemini is unreachable from the backend.") from exc

    parts = body.get("candidates", [{}])[0].get("content", {}).get("parts", [])
    text = "".join(part.get("text", "") for part in parts).strip()
    if not text:
        raise GeminiGenerationError("Gemini returned an empty response.")

    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise GeminiGenerationError("Gemini did not return valid JSON.") from exc


def _clean_question(question):
    options = [str(option).strip() for option in question.get("options", []) if str(option).strip()]
    correct_index = int(question.get("correct_index", 0) or 0)
    if not options:
        options = ["Option A", "Option B", "Option C", "Option D"]
    if correct_index >= len(options):
        correct_index = 0
    return {
        "prompt": str(question.get("prompt", "")).strip() or "Question generated by AI",
        "options": options[:6],
        "correct_index": correct_index,
    }


def generate_module_package(*, prompt: str, course_title: str, category: str, level: str, module_title: str = ""):
    query = f"""
You are generating a JSON payload for an LMS instructor editor.
Return only valid JSON with this shape:
{{
  "title": "string",
  "description": "string",
  "learning_objectives": ["string"],
  "estimated_minutes": 0,
  "is_published": false,
  "lessons": [
    {{
      "title": "string",
      "content": "string",
      "lesson_type": "VIDEO|TEXT|QUIZ|ASSIGNMENT|LIVE|DOWNLOAD",
      "status": "DRAFT|PUBLISHED",
      "video_url": "string",
      "transcript": "string",
      "instructor_notes": "string",
      "duration_seconds": 0,
      "is_preview": false
    }}
  ],
  "quiz": {{
    "title": "string",
    "passing_score": 70,
    "time_limit_minutes": 10,
    "questions": [
      {{
        "prompt": "string",
        "options": ["string"],
        "correct_index": 0
      }}
    ]
  }}
}}
Constraints:
- Create 3 to 5 lessons.
- Fill every field.
- Keep status as DRAFT unless clearly requested.
- Use realistic lesson durations.
- Quiz must include 4 questions.
Context:
course_title={course_title}
category={category}
level={level}
module_title={module_title}
instructor_prompt={prompt}
"""
    response = _request_json(query)
    lessons = response.get("lessons", [])
    quiz = response.get("quiz") or {}
    return {
        "title": str(response.get("title", "")).strip() or module_title or "AI Generated Module",
        "description": str(response.get("description", "")).strip(),
        "learning_objectives": [str(item).strip() for item in response.get("learning_objectives", []) if str(item).strip()],
        "estimated_minutes": max(int(response.get("estimated_minutes", 0) or 0), 15),
        "is_published": bool(response.get("is_published", False)),
        "lessons": [
            {
                "title": str(lesson.get("title", "")).strip() or f"Lesson {index + 1}",
                "content": str(lesson.get("content", "")).strip(),
                "lesson_type": str(lesson.get("lesson_type", "VIDEO")).strip() or "VIDEO",
                "status": str(lesson.get("status", "DRAFT")).strip() or "DRAFT",
                "video_url": str(lesson.get("video_url", "")).strip(),
                "transcript": str(lesson.get("transcript", "")).strip(),
                "instructor_notes": str(lesson.get("instructor_notes", "")).strip(),
                "duration_seconds": max(int(lesson.get("duration_seconds", 0) or 0), 300),
                "is_preview": bool(lesson.get("is_preview", False)),
            }
            for index, lesson in enumerate(lessons[:5])
        ],
        "quiz": {
            "title": str(quiz.get("title", "")).strip() or "Module Quiz",
            "passing_score": min(max(int(quiz.get("passing_score", 70) or 70), 1), 100),
            "time_limit_minutes": max(int(quiz.get("time_limit_minutes", 10) or 10), 1),
            "questions": [_clean_question(question) for question in quiz.get("questions", [])[:6]],
        },
    }


def generate_lesson_package(*, prompt: str, course_title: str, category: str, level: str, module_title: str, lesson_title: str = ""):
    query = f"""
You are generating a JSON payload for an LMS lesson editor.
Return only valid JSON with this shape:
{{
  "title": "string",
  "content": "string",
  "lesson_type": "VIDEO|TEXT|QUIZ|ASSIGNMENT|LIVE|DOWNLOAD",
  "status": "DRAFT|PUBLISHED",
  "video_url": "string",
  "transcript": "string",
  "instructor_notes": "string",
  "duration_seconds": 0,
  "is_preview": false,
  "quiz": {{
    "title": "string",
    "passing_score": 70,
    "time_limit_minutes": 10,
    "questions": [
      {{
        "prompt": "string",
        "options": ["string"],
        "correct_index": 0
      }}
    ]
  }}
}}
Constraints:
- Fill every lesson field.
- Keep status as DRAFT unless the prompt explicitly asks for publish-ready content.
- Quiz must include 4 questions.
Context:
course_title={course_title}
category={category}
level={level}
module_title={module_title}
lesson_title={lesson_title}
instructor_prompt={prompt}
"""
    response = _request_json(query)
    quiz = response.get("quiz") or {}
    return {
        "title": str(response.get("title", "")).strip() or lesson_title or "AI Generated Lesson",
        "content": str(response.get("content", "")).strip(),
        "lesson_type": str(response.get("lesson_type", "VIDEO")).strip() or "VIDEO",
        "status": str(response.get("status", "DRAFT")).strip() or "DRAFT",
        "video_url": str(response.get("video_url", "")).strip(),
        "transcript": str(response.get("transcript", "")).strip(),
        "instructor_notes": str(response.get("instructor_notes", "")).strip(),
        "duration_seconds": max(int(response.get("duration_seconds", 0) or 0), 300),
        "is_preview": bool(response.get("is_preview", False)),
        "quiz": {
            "title": str(quiz.get("title", "")).strip() or "Lesson Quiz",
            "passing_score": min(max(int(quiz.get("passing_score", 70) or 70), 1), 100),
            "time_limit_minutes": max(int(quiz.get("time_limit_minutes", 10) or 10), 1),
            "questions": [_clean_question(question) for question in quiz.get("questions", [])[:6]],
        },
    }

